frontend:
  - 'src/**/*'
  - 'public/**/*'

workflow:
  - '.github/workflows/*'

config:
  - 'package.json'
  - 'tsconfig.json'
  - 'rslib.config.ts'
  - 'eslint.config.*'
  - 'yarn.lock'
  - '.github/labeler.yml'

docs:
  - '**/*.md'
